### ISSUE TITLE
deferred code chunk output

### ISSUE THREAD

**Issue by nicholasjhorton** [ismayc/rticles#1]
It might be nice to include some examples for where the code and output are hidden from code chunks (and deferred to show up in an appendix).  This would involve some combination of:

<<loadknitr, echo=FALSE>>=
require(knitr)
options(width=60)
@

in the main document and

\chapter{Appendix}
\label{ch:appendix}

<<"all-blocks",results = 'hide',fig.width=5,fig.height=3,echo=TRUE>>=
<<loadknitr>>
<<load2>>
<<xtable>>
<<setup1>>
<<barplot1a>>
<<barplot2a>>
<<effect1>>
<<effect2>>
<<effect3>>
<<effect4>>
<<effect5>>
<<effect6>>
@

in the appendix

**Comment by ismayc** [comment]
Great idea!  I'll add that when I get a chance over the next couple weeks.

**Comment by ismayc** [comment]
This has now been implemented.  Since this is Markdown instead of `knitr` I used

``````
 ```{r ref.label = 'include_packages', results = 'hide', echo = TRUE}
 ```
``````

instead of the <<>> syntax.  Please let me know if there are any other issues or things you'd like implemented.  Thanks again, @nicholasjhorton!
